---
engines:
  checkstyle:
    enabled: true
    channel: beta
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.java"
  - "**.css"
  - "**.js"
exclude_paths: []
